"Resource/UI/HoldoutCoopFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"180" [$ENGLISH]
		"wide"					"270" [$!ENGLISH]
		"tall"					"85"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnQuickMatch"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnQuickMatch"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnPlayHoldoutCoopLeaderboards"
		"navDown"				"BtnPlayHoldoutCoopWithAnyone"
		"labelText"				"#L4D360UI_QuickMatch"
		"tooltiptext"			"#L4D360UI_QuickMatch_HoldoutCoop_Tip"
		"disabled_tooltiptext"	"#L4D360UI_QuickMatch_Tip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"QuickMatchHoldoutCoop"
	}
	
	"BtnPlayHoldoutCoopWithAnyone"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnPlayHoldoutCoopWithAnyone"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnQuickMatch"
		"navDown"				"BtnPlayHoldoutCoopWithFriends"
		"labelText"				"#L4D360UI_CustomMatch"	[$X360]
		"labelText"				"#L4D360UI_MainMenu_PlayOnline" [$WIN32]
		"tooltiptext"			"#L4D360UI_MainMenu_PlayHoldoutCoopWithAnyone_Tip"
		"disabled_tooltiptext"	"#L4D360UI_MainMenu_PlayHoldoutCoopWithAnyone_Tip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"PlayHoldoutCoopWithAnyone"
	}	
	
	"BtnPlayHoldoutCoopWithFriends"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnPlayHoldoutCoopWithFriends"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnPlayHoldoutCoopWithAnyone"
		"navDown"				"BtnPlayHoldoutCoopLeaderboards"
		"labelText"				"#L4D360UI_MainMenu_PlayCoopWithFriends"
		"tooltiptext"			"#L4D360UI_MainMenu_PlayCoopWithFriends_Tip"
		"disabled_tooltiptext"	"#L4D360UI_MainMenu_PlayCoopWithFriends_Tip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"PlayHoldoutCoopWithFriends"
	}

	"BtnPlayHoldoutCoopLeaderboards"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnPlayHoldoutCoopLeaderboards"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnPlayHoldoutCoopWithFriends"
		"navDown"				"BtnQuickMatch"
		"labelText"				"#L4D360UI_MainMenu_HoldoutCoopLeaderboards"
		"tooltiptext"			"#L4D360UI_MainMenu_HoldoutCoopLeaderboards_Tip"
		"disabled_tooltiptext"	"#L4D360UI_MainMenu_HoldoutCoopLeaderboards_Tip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"PlayHoldoutCoopLeaderboards"
	}
}